### PR TITLE
Callbacks can now accept an argument of the interface type.

### PR DESCRIPTION
**Pull request by float64co**

### CODE REVIEW

**Comment by liamzdenek** [comment]
What's the use case for this change?

Currently, variables can be passed through scope capturing, eg:

``` go
arg := "World"
thread := pthread.Create(func() {
    fmt.Printf("Hello, %s\n", arg);
});
```

**Comment by float64co** [comment]
Prevents leaving client connections lying around in the calling goroutine, they can just be sent directly to Create.

Makes the behavior of changing the value of arg from your example readily apparent.

**Comment by LukeB42** [comment]
Prevents leaving client connections lying around in the calling goroutine, they can just be sent directly to Create.

Makes the behavior of changing the value of arg from your example readily apparent.

**Comment by LukeB42** [comment]
Prevents leaving client connections lying around in the calling goroutine, they can just be sent directly to Create.

Makes the behavior of changing the value of arg from your example readily apparent.

**Comment by liamzdenek** [comment]
Closed as Wont Fix. This change breaks reverse-compatibility for a project that has been stable for several years. It's possible to make this change without breaking reverse-compat, but I don't know what problem this could solve, or why scope capturing is insufficient. Unless there is a good reason, this change belongs in a fork.

(As an aside, this change was performed dangerously. Using two channels to transfer the interface{} argument means that they could become out of sync, and the wrong argument could be matched with the wrong function, particularly if many threads are started concurrently)

**Comment by float64co** [comment]
OK. Glad this is still maintained. Cheers Liam.

**Pull request closed without merging**
